accepted = [
  "Apache-2.0",
  "Apache-2.0 WITH LLVM-exception",
  "MIT",
  "MPL-2.0",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "ISC",
  "NCSA",
  "Unicode-3.0",
  "Unicode-DFS-2016",
  "Zlib",
  "CC0-1.0",
  "0BSD",
  "Unlicense",
  "BSL-1.0",
  "CDLA-Permissive-2.0",
  "OpenSSL",
]

targets = [
  "x86_64-unknown-linux-gnu",
  "x86_64-pc-windows-msvc",
  "x86_64-apple-darwin",
]

ignore-build-dependencies = false
ignore-dev-dependencies = false
ignore-transitive-dependencies = false
filter-noassertion = true
no-clearly-defined = true

private = { ignore = true }
