import type { AppSettings } from '../../api/client'

export function makeDefaultFormData(overrides?: Partial<AppSettings>): AppSettings {
  return {
    retention_days: 30,
    max_storage_mb: 500,
    web_port: 10090,
    allow_external: false,
    capture_enabled: true,
    idle_threshold_secs: 300,
    metrics_interval_secs: 5,
    process_interval_secs: 10,
    notification: {
      enabled: true,
      idle_notification: true,
      idle_notification_mins: 30,
      long_session_notification: true,
      long_session_mins: 60,
      high_usage_notification: false,
      high_usage_threshold: 90,
    },
    update: {
      enabled: true,
      check_interval_hours: 24,
      include_prerelease: false,
      channel: 'stable',
      auto_install: false,
    },
    telemetry: {
      enabled: true,
      crash_reports: true,
      usage_analytics: false,
      performance_metrics: true,
    },
    monitor: {
      process_monitoring: true,
      input_activity: true,
      privacy_mode: false,
    },
    privacy: {
      auto_exclude_sensitive: true,
      pii_filter_level: 'Standard',
      excluded_apps: [],
      excluded_app_patterns: [],
      excluded_title_patterns: [],
    },
    schedule: {
      active_hours_enabled: true,
      active_start_hour: 9,
      active_end_hour: 18,
      active_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
      pause_on_screen_lock: true,
      pause_on_battery_saver: false,
    },
    automation: {
      enabled: false,
    },
    sandbox: {
      enabled: true,
      profile: 'Standard',
      allowed_read_paths: [],
      allowed_write_paths: [],
      allow_network: false,
      max_memory_bytes: 536870912,
      max_cpu_time_ms: 30000,
    },
    ai_provider: {
      access_mode: 'local',
      ocr_provider: 'tesseract',
      llm_provider: 'none',
      external_data_policy: 'redacted_only',
      allow_unredacted_external_ocr: false,
      ocr_validation: { enabled: false, min_confidence: 0.7, max_invalid_ratio: 0.3 },
      scene_action_override: { enabled: false, reason: '', approved_by: '', expires_at: null },
      scene_intelligence: {
        enabled: false,
        overlay_enabled: false,
        allow_action_execution: false,
        min_confidence: 0.6,
        max_elements: 50,
        calibration_enabled: false,
        calibration_min_elements: 5,
        calibration_min_avg_confidence: 0.7,
      },
      fallback_to_local: true,
      ocr_api: null,
      llm_api: null,
      active_profile_id: null,
      saved_profiles: [],
    },
    ai_session: {
      max_concurrent_sessions: 3,
      idle_timeout_secs: 300,
      session_timeout_secs: 600,
      max_retries: 3,
      max_history_turns: 100,
      health_check_interval_secs: 30,
    },
    suggestion: { enabled: true },
    indicator: { show_border: true, show_panel: true, border_opacity: 0.6 },
    analysis: {
      enabled: true,
      interval_secs: 60,
      min_confidence: 0.5,
      max_suggestions: 5,
      embedding_enabled: true,
      gui_intelligence_enabled: true,
      text_intelligence_enabled: true,
      auto_tuner_enabled: false,
    },
    network: {
      server_base_url: 'http://localhost:8000',
      request_timeout_ms: 30000,
      grpc_enabled: false,
      grpc_endpoint: 'http://localhost:50051',
      tls_enabled: false,
    },
    coaching: {
      enabled: true,
      tone: 'Gentle',
      quiet_hours: [],
      profiles: {
        FocusGuard: { enabled: true, min_interval_secs: 300 },
        TimeAware: { enabled: true, min_interval_secs: 300 },
        DeepWorkCoach: { enabled: true, min_interval_secs: 300 },
        ContextRestore: { enabled: true, min_interval_secs: 300 },
        GoalTracker: { enabled: true, min_interval_secs: 300 },
      },
      regime_goals: {},
      locale: 'en',
      overlay_mode: 'Minimal',
    },
    integration: { enabled: false, auth_profile_kind: 'None', request_timeout_secs: 30, sync_interval_secs: 60 },
    sync: {
      enabled: false,
      transport: 'None',
      interval_secs: 300,
      device_name: '',
      lan_advertise: false,
      compression_enabled: true,
    },
    audio: {
      enabled: false,
      whisper_model_path: '',
      language: 'auto',
      max_recording_secs: 60,
      model_size: 'base',
      stt_provider: 'local',
      cloud_api_key: '',
      cloud_stt_endpoint: 'https://api.openai.com/v1/audio/transcriptions',
      cloud_timeout_secs: 10,
      mic_input_mode: 'push_to_talk',
      vad_threshold: 0.02,
      vad_silence_ms: 800,
      vad_min_speech_ms: 300,
    },
    focus_auto: {
      enabled: false,
      duration_minutes: 25,
      trigger_apps: [],
      trigger_schedules: [],
      cooldown_secs: 300,
    },
    ...overrides,
  }
}
