import type { AppSettings } from '../../api/client'

export function makeDefaultFormData(overrides?: Partial<AppSettings>): AppSettings {
  return {
    retention_days: 30,
    max_storage_mb: 500,
    web_port: 10090,
    allow_external: false,
    capture_enabled: true,
    idle_threshold_secs: 300,
    metrics_interval_secs: 5,
    process_interval_secs: 10,
    notification: {
      enabled: true,
      idle_notification: true,
      idle_notification_mins: 30,
      long_session_notification: true,
      long_session_mins: 60,
      high_usage_notification: false,
      high_usage_threshold: 90,
    },
    update: {
      enabled: true,
      check_interval_hours: 24,
      include_prerelease: false,
      auto_install: false,
    },
    telemetry: {
      enabled: true,
      crash_reports: true,
      usage_analytics: false,
      performance_metrics: true,
    },
    monitor: {
      process_monitoring: true,
      input_activity: true,
      privacy_mode: false,
    },
    privacy: {
      auto_exclude_sensitive: true,
      pii_filter_level: 'Standard',
      excluded_apps: [],
      excluded_app_patterns: [],
      excluded_title_patterns: [],
    },
    schedule: {
      active_hours_enabled: true,
      active_start_hour: 9,
      active_end_hour: 18,
      active_days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
      pause_on_screen_lock: true,
      pause_on_battery_saver: false,
    },
    automation: {
      enabled: false,
    },
    sandbox: {
      enabled: true,
      profile: 'Standard',
      allowed_read_paths: [],
      allowed_write_paths: [],
      allow_network: false,
      max_memory_bytes: 536870912,
      max_cpu_time_ms: 30000,
    },
    ai_provider: {
      access_mode: 'local',
      ocr_provider: 'tesseract',
      llm_provider: 'none',
      external_data_policy: 'redacted_only',
      allow_unredacted_external_ocr: false,
      ocr_validation: { enabled: false, min_confidence: 0.7, max_invalid_ratio: 0.3 },
      scene_action_override: { enabled: false, reason: '', approved_by: '', expires_at: null },
      scene_intelligence: {
        enabled: false,
        overlay_enabled: false,
        allow_action_execution: false,
        min_confidence: 0.6,
        max_elements: 50,
        calibration_enabled: false,
        calibration_min_elements: 5,
        calibration_min_avg_confidence: 0.7,
      },
      fallback_to_local: true,
      ocr_api: null,
      llm_api: null,
      active_profile_id: null,
      saved_profiles: [],
    },
    ...overrides,
  }
}
