#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
ARTIFACT_DIR="${ROOT_DIR}/artifacts/integrity"
CARGO_CMD="$ROOT_DIR/scripts/cargo-cache.sh"
VET_MODE="${INTEGRITY_VET_MODE:-advisory}"

mkdir -p "${ARTIFACT_DIR}"

require_cmd() {
  if ! command -v "$1" >/dev/null 2>&1; then
    printf "Missing required command: %s\n" "$1" >&2
    exit 1
  fi
}

require_cmd cargo

case "$VET_MODE" in
  strict|advisory) ;;
  *)
    printf "Invalid INTEGRITY_VET_MODE: %s (expected strict|advisory)\n" "$VET_MODE" >&2
    exit 1
    ;;
esac

if ! command -v cargo-audit >/dev/null 2>&1; then
  printf "cargo-audit is required. Install: cargo install cargo-audit --locked\n" >&2
  exit 1
fi

if ! command -v cargo-deny >/dev/null 2>&1; then
  printf "cargo-deny is required. Install: cargo install cargo-deny --locked\n" >&2
  exit 1
fi

if ! command -v cargo-vet >/dev/null 2>&1; then
  printf "cargo-vet is required. Install: cargo install cargo-vet --locked\n" >&2
  exit 1
fi

if ! command -v cargo-cyclonedx >/dev/null 2>&1; then
  printf "cargo-cyclonedx is required. Install: cargo install cargo-cyclonedx --locked\n" >&2
  exit 1
fi

cd "${ROOT_DIR}"

"$CARGO_CMD" test -p oneshim-core update_integrity_policy
"$CARGO_CMD" test -p oneshim-app integrity_guard
"$CARGO_CMD" test -p oneshim-app verify_signature_
# RUSTSEC-2024-0429 is a GTK3/glib transitive advisory from the Linux Tauri stack.
# We cannot remediate it without an upstream stack migration, so keep it explicit.
"$CARGO_CMD" audit --ignore RUSTSEC-2024-0429
"$CARGO_CMD" deny check licenses advisories sources bans
if [[ "$VET_MODE" == "strict" ]]; then
  "$CARGO_CMD" vet check
else
  if ! "$CARGO_CMD" vet check; then
    printf "[integrity] cargo-vet advisory failed (strict mode remains enforced on push/schedule).\n" >&2
  fi
fi

find "${ROOT_DIR}/crates" -name 'sbom.cdx.json' -delete
"$CARGO_CMD" cyclonedx --format json --override-filename sbom.cdx --manifest-path Cargo.toml

sbom_count=0
while IFS= read -r sbom_path; do
  crate_name="$(basename "$(dirname "${sbom_path}")")"
  cp "${sbom_path}" "${ARTIFACT_DIR}/${crate_name}.sbom.cdx.json"
  sbom_count=$((sbom_count + 1))
done < <(find "${ROOT_DIR}/crates" -name 'sbom.cdx.json' | sort)

if [ "${sbom_count}" -eq 0 ]; then
  printf "No SBOM files were generated by cargo-cyclonedx\n" >&2
  exit 1
fi

printf "Integrity verification completed.\n"
