import type { ProviderSurfaceCatalog } from './contracts'

export const DEFAULT_PROVIDER_SURFACE_CATALOG: ProviderSurfaceCatalog = {
  version: 2,
  updated_at: '2026-03-16T00:30:00Z',
  vendors: [
    { vendor_id: 'anthropic', provider_type: 'Anthropic', aliases: ['anthropic'], display_name: 'Anthropic' },
    {
      vendor_id: 'openai',
      provider_type: 'OpenAi',
      aliases: ['openai', 'open_ai', 'open-ai', 'openai-compatible'],
      display_name: 'OpenAI',
    },
    { vendor_id: 'google', provider_type: 'Google', aliases: ['google', 'gemini'], display_name: 'Google' },
    { vendor_id: 'generic', provider_type: 'Generic', aliases: ['generic'], display_name: 'Generic' },
  ],
  surfaces: [
    {
      surface_id: 'provider_surface.anthropic.direct_api',
      vendor_id: 'anthropic',
      provider_type: 'Anthropic',
      display_name: 'Anthropic API',
      execution_kind: 'direct_http',
      credential_kind: 'api_key',
      stability: 'ga',
      preferred_for_product_auth: false,
      catalog_strategy: 'http_models_endpoint',
      supports: { llm: true, ocr: true, model_catalog: true, context_bridge: false },
      default_models: {
        llm_models: ['claude-sonnet-4-20250514', 'claude-opus-4-1-20250805', 'claude-opus-4-20250514'],
        ocr_models: ['claude-sonnet-4-20250514', 'claude-opus-4-1-20250805', 'claude-opus-4-20250514'],
      },
      parameter_profiles: {
        llm: { supported: [], unsupported: [], notes: [] },
        ocr: { supported: [], unsupported: [], notes: [] },
      },
      llm_transport: {
        method: 'POST',
        url: 'https://api.anthropic.com/v1/messages',
        auth_scheme: 'x_api_key',
        request_shape: 'anthropic_messages',
      },
      ocr_transport: {
        method: 'POST',
        url: 'https://api.anthropic.com/v1/messages',
        auth_scheme: 'x_api_key',
        request_shape: 'anthropic_vision_messages',
      },
      model_catalog_transport: {
        method: 'GET',
        url: 'https://api.anthropic.com/v1/models',
        auth_scheme: 'x_api_key',
        response_shape: 'standard_data_or_models',
        llm_supported: true,
        ocr_supported: true,
      },
      references: [],
    },
    {
      surface_id: 'provider_surface.openai.direct_api',
      vendor_id: 'openai',
      provider_type: 'OpenAi',
      display_name: 'OpenAI API',
      execution_kind: 'direct_http',
      credential_kind: 'api_key',
      stability: 'ga',
      preferred_for_product_auth: false,
      catalog_strategy: 'http_models_endpoint',
      supports: { llm: true, ocr: true, model_catalog: true, context_bridge: false },
      default_models: { llm_models: ['gpt-5.4', 'gpt-5.2', 'gpt-5-mini'], ocr_models: ['gpt-5.4', 'gpt-5-mini'] },
      parameter_profiles: {
        llm: { supported: [], unsupported: [], notes: [] },
        ocr: { supported: [], unsupported: [], notes: [] },
      },
      llm_transport: {
        method: 'POST',
        url: 'https://api.openai.com/v1/responses',
        auth_scheme: 'bearer',
        request_shape: 'openai_responses',
      },
      ocr_transport: {
        method: 'POST',
        url: 'https://api.openai.com/v1/chat/completions',
        auth_scheme: 'bearer',
        request_shape: 'openai_vision_chat_completions',
      },
      model_catalog_transport: {
        method: 'GET',
        url: 'https://api.openai.com/v1/models',
        auth_scheme: 'bearer',
        response_shape: 'standard_data_or_models',
        llm_supported: true,
        ocr_supported: true,
      },
      references: [],
    },
    {
      surface_id: 'provider_surface.openai.subprocess_cli',
      vendor_id: 'openai',
      provider_type: 'OpenAi',
      display_name: 'Codex CLI',
      execution_kind: 'subprocess_cli',
      credential_kind: 'cli_subscription',
      stability: 'preview',
      preferred_for_product_auth: true,
      catalog_strategy: 'subprocess_probe',
      supports: { llm: true, ocr: false, model_catalog: false, context_bridge: true },
      default_models: { llm_models: ['gpt-5.4', 'gpt-5.2-codex', 'gpt-5.2'], ocr_models: [] },
      parameter_profiles: {
        llm: { supported: [], unsupported: [], notes: [] },
        ocr: { supported: [], unsupported: [], notes: [] },
      },
      subprocess_transport: {
        executable_candidates: ['codex'],
        auth_probe_command: ['login', 'status'],
        invocation_mode: 'codex_exec_json',
        model_flag: '--model',
        json_output_supported: true,
      },
      references: [],
    },
    {
      surface_id: 'provider_surface.google.direct_api',
      vendor_id: 'google',
      provider_type: 'Google',
      display_name: 'Google Gemini API',
      execution_kind: 'direct_http',
      credential_kind: 'api_key',
      stability: 'ga',
      preferred_for_product_auth: false,
      catalog_strategy: 'google_models_endpoint',
      supports: { llm: true, ocr: true, model_catalog: true, context_bridge: false },
      default_models: {
        llm_models: ['gemini-2.5-flash', 'gemini-2.5-pro', 'gemini-2.5-flash-lite', 'gemini-3-flash-preview', 'gemini-3-pro-preview'],
        ocr_models: [],
      },
      parameter_profiles: {
        llm: { supported: [], unsupported: [], notes: [] },
        ocr: { supported: [], unsupported: [], notes: [] },
      },
      llm_transport: {
        method: 'POST',
        url: 'https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent',
        auth_scheme: 'x_goog_api_key',
        request_shape: 'google_generate_content',
      },
      ocr_transport: {
        method: 'POST',
        url: 'https://vision.googleapis.com/v1/images:annotate',
        auth_scheme: 'x_goog_api_key',
        request_shape: 'google_vision_annotate',
      },
      model_catalog_transport: {
        method: 'GET',
        url: 'https://generativelanguage.googleapis.com/v1beta/models',
        auth_scheme: 'x_goog_api_key',
        response_shape: 'google_models',
        llm_supported: true,
        ocr_supported: false,
        ocr_notice: 'Google Vision OCR endpoint does not expose a selectable model catalog.',
      },
      references: [],
    },
    {
      surface_id: 'provider_surface.google.subprocess_cli',
      vendor_id: 'google',
      provider_type: 'Google',
      display_name: 'Gemini CLI',
      execution_kind: 'subprocess_cli',
      credential_kind: 'cli_subscription',
      stability: 'preview',
      preferred_for_product_auth: true,
      catalog_strategy: 'subprocess_probe',
      supports: { llm: true, ocr: false, model_catalog: false, context_bridge: true },
      default_models: { llm_models: ['gemini-2.5-pro', 'gemini-2.5-flash', 'gemini-3-flash-preview'], ocr_models: [] },
      parameter_profiles: {
        llm: { supported: [], unsupported: [], notes: [] },
        ocr: { supported: [], unsupported: [], notes: [] },
      },
      subprocess_transport: {
        executable_candidates: ['gemini', 'gemini-cli'],
        auth_probe_command: [],
        invocation_mode: 'gemini_cli_json',
        model_flag: '--model',
        json_output_supported: true,
      },
      references: [],
    },
    {
      surface_id: 'provider_surface.generic.direct_api',
      vendor_id: 'generic',
      provider_type: 'Generic',
      display_name: 'Generic OpenAI-compatible API',
      execution_kind: 'direct_http',
      credential_kind: 'api_key',
      stability: 'ga',
      preferred_for_product_auth: false,
      catalog_strategy: 'http_models_endpoint',
      supports: { llm: true, ocr: true, model_catalog: true, context_bridge: false },
      default_models: { llm_models: ['gpt-5-mini', 'gpt-5.4'], ocr_models: ['gpt-5-mini'] },
      parameter_profiles: {
        llm: { supported: [], unsupported: [], notes: [] },
        ocr: { supported: [], unsupported: [], notes: [] },
      },
      llm_transport: {
        method: 'POST',
        url: 'https://api.openai.com/v1/chat/completions',
        auth_scheme: 'bearer',
        request_shape: 'openai_chat_completions',
      },
      ocr_transport: {
        method: 'POST',
        url: 'https://api.openai.com/v1/chat/completions',
        auth_scheme: 'bearer',
        request_shape: 'openai_vision_chat_completions',
      },
      model_catalog_transport: {
        method: 'GET',
        url: 'https://api.openai.com/v1/models',
        auth_scheme: 'bearer',
        response_shape: 'standard_data_or_models',
        llm_supported: true,
        ocr_supported: true,
      },
      references: [],
    },
  ],
}
